// Deterministic rounded-rect lens displacement map. Builtins only (node:zlib).
// Run:   tsx scripts/gen-glass-lens-map.ts
// Check: tsx scripts/gen-glass-lens-map.ts --check   (CI drift guard; exits 1 on mismatch)
//
// Output: src/components/glass/glass-lens-map.generated.ts exporting GLASS_LENS_MAP
// (a data:image/png;base64,... string). The runtime ONLY imports that string — there
// is provably no mount-time canvas, so the static-filter-buffer contract holds.
import { deflateSync } from "node:zlib"
import { writeFileSync, readFileSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const W = 256, H = 256, R = 40, BAND = 56, MAG = 1.0

// signed distance to a rounded rect centered in WxH (<0 inside, ~0 at rim, >0 outside)
function sdf(x: number, y: number): number {
  const qx = Math.abs(x - W / 2) - (W / 2 - R)
  const qy = Math.abs(y - H / 2) - (H / 2 - R)
  const ax = Math.max(qx, 0), ay = Math.max(qy, 0)
  return Math.hypot(ax, ay) + Math.min(Math.max(qx, qy), 0) - R
}

const rgba = Buffer.alloc(W * H * 4)
function put(x: number, y: number, nx: number, ny: number, m: number) {
  const i = (y * W + x) * 4
  rgba[i]     = Math.max(0, Math.min(255, Math.round(128 + nx * m * 110))) // R horizontal
  rgba[i + 1] = Math.max(0, Math.min(255, Math.round(128 + ny * m * 110))) // G vertical
  rgba[i + 2] = 128                                                        // B unused / neutral
  rgba[i + 3] = 255                                                        // A opaque
}

for (let y = 0; y <= H / 2; y++) {
  for (let x = 0; x <= W / 2; x++) {
    const dist = sdf(x, y)
    // strength: 0 deep inside, peaks IN the rim band, 0 outside the box. eased (t^2).
    const inRim = dist > -BAND && dist < 0
    const tt = inRim ? (1 - Math.min(Math.max(-dist / BAND, 0), 1)) : 0
    const m = tt * tt * MAG
    // inward unit normal from SDF gradient
    const gx = (sdf(x + 1, y) - sdf(x - 1, y)) / 2
    const gy = (sdf(x, y + 1) - sdf(x, y - 1)) / 2
    const len = Math.hypot(gx, gy) || 1
    const ux = -gx / len, uy = -gy / len    // point inward (toward center)
    put(x, y, ux, uy, m)                      // TL
    put(W - 1 - x, y, -ux, uy, m)             // TR: flip R
    put(x, H - 1 - y, ux, -uy, m)             // BL: flip G
    put(W - 1 - x, H - 1 - y, -ux, -uy, m)    // BR: flip both
  }
}

// ---- hand-rolled PNG (signature + IHDR + IDAT + IEND), no deps ----
function crc32(buf: Buffer): number {
  let c = ~0
  for (let n = 0; n < buf.length; n++) {
    c ^= buf[n] ?? 0
    for (let k = 0; k < 8; k++) c = (c >>> 1) ^ (0xedb88320 & -(c & 1))
  }
  return (~c) >>> 0
}
function chunk(type: string, data: Buffer): Buffer {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length, 0)
  const body = Buffer.concat([Buffer.from(type, "latin1"), data])
  const crc = Buffer.alloc(4); crc.writeUInt32BE(crc32(body), 0)
  return Buffer.concat([len, body, crc])
}
const sig = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])
const ihdr = Buffer.alloc(13)
ihdr.writeUInt32BE(W, 0); ihdr.writeUInt32BE(H, 4)
ihdr[8] = 8; ihdr[9] = 6; ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0 // 8-bit, RGBA, no interlace
// prepend per-scanline filter byte (0 = None)
const raw = Buffer.alloc(H * (1 + W * 4))
for (let y = 0; y < H; y++) {
  raw[y * (1 + W * 4)] = 0
  rgba.copy(raw, y * (1 + W * 4) + 1, y * W * 4, (y + 1) * W * 4)
}
const idat = deflateSync(raw, { level: 9 })
const png = Buffer.concat([sig, chunk("IHDR", ihdr), chunk("IDAT", idat), chunk("IEND", Buffer.alloc(0))])
const dataUri = "data:image/png;base64," + png.toString("base64")

const out =
  `// AUTO-GENERATED by scripts/gen-glass-lens-map.ts — do not edit by hand.\n` +
  `// Rounded-rect lens displacement map (R=horiz normal, G=vert normal, 128 neutral, B=128, A=255).\n` +
  `// Regenerate: \`tsx scripts/gen-glass-lens-map.ts\`  Drift-check: \`tsx scripts/gen-glass-lens-map.ts --check\`.\n` +
  `export const GLASS_LENS_MAP = ${JSON.stringify(dataUri)} as const\n`

const __dir = dirname(fileURLToPath(import.meta.url))
const target = resolve(__dir, "../src/components/glass/glass-lens-map.generated.ts")
if (process.argv.includes("--check")) {
  const cur = readFileSync(target, "utf8")
  if (cur !== out) { console.error("glass-lens map drift — re-run: tsx scripts/gen-glass-lens-map.ts"); process.exit(1) }
  console.log("glass-lens map up to date"); process.exit(0)
}
writeFileSync(target, out)
console.log("wrote", target, "png bytes:", png.length)
